# Generated by Django 5.2 on 2026-05-30 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_group_delete_enrollment'),
        ('instructors', '0001_initial'),
        ('students', '0002_alter_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('frozen', 'Muzlatilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'liq to'langan"), ('overdue', "Muddati o'tgan"), ('refunded', 'Qaytarilgan')], default='unpaid', max_length=20, verbose_name="To'lov holati")),
                ('course_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kurs narxi')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan summa")),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yozilgan vaqt')),
                ('source', models.CharField(choices=[('walk_in', 'Bevosita'), ('referral', "Do'st tavsiyasi"), ('social', 'Ijtimoiy tarmoq'), ('website', 'Sayt'), ('phone', 'Telefon'), ('other', 'Boshqa')], default='walk_in', max_length=20, verbose_name='Manba')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.group', verbose_name='Guruh')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='instructors.instructor', verbose_name="O'qituvchi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Ro'yxatga olish",
                'verbose_name_plural': "Ro'yxatga olishlar",
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_notes', to='enrollments.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
