# Generated by Django 6.0.3 on 2026-06-02 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Fully paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='unpaid', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('referral', 'Referral'), ('social', 'Social media'), ('website', 'Website'), ('phone', 'Phone'), ('other', 'Other')], default='walk_in', max_length=20, verbose_name='Manba'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('frozen', 'Frozen')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.CreateModel(
            name='TelegramLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('telegram_username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processed', "Ro'yxatga olingan"), ('rejected', 'Rad etilgan')], default='new', max_length=20, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='enrollments.enrollment', verbose_name='Yaratilgan enrollment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram ariza',
                'verbose_name_plural': 'Telegram arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
