# Generated by Django 6.0.3 on 2026-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFSMState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=190, unique=True)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot FSM holati',
                'verbose_name_plural': 'Bot FSM holatlari',
            },
        ),
    ]
