# Generated by Django 5.2 on 2026-05-30 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_id_alter_enrollment_id_alter_student_id_and_more'),
        ('instructors', '0001_initial'),
        ('students', '0002_alter_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma')),
                ('payment_month', models.PositiveSmallIntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], default=5, verbose_name="To'lov oyi")),
                ('payment_year', models.PositiveSmallIntegerField(default=2026, verbose_name="To'lov yili")),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi"), ('online', "Online to'lov")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('paid', "To'langan"), ('pending', 'Kutilmoqda'), ('partial', "Qisman to'langan"), ('overdue', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='paid', max_length=20, verbose_name='Holat')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='instructors.instructor', verbose_name="O'qituvchi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-paid_at'],
            },
        ),
    ]
