# Generated by Django 6.0.3 on 2026-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank transfer'), ('online', 'Online payment')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6, verbose_name="To'lov oyi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partially paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='paid', max_length=20, verbose_name='Holat'),
        ),
    ]
