# Generated by Django 6.0.3 on 2026-06-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10)),
                ('provider_tx_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Provayder tranzaksiya ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('state', models.IntegerField(default=1)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': "Onlayn to'lov tranzaksiyasi",
                'verbose_name_plural': "Onlayn to'lov tranzaksiyalari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_tx_id'], name='payments_pa_provide_e97ec6_idx')],
            },
        ),
    ]
