# Generated by Django 6.0.3 on 2026-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='churn_risk_reason',
            field=models.TextField(blank=True, default='', verbose_name='Churn risk sababi (AI)'),
        ),
        migrations.AddField(
            model_name='student',
            name='churn_risk_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Churn risk (0-100)'),
        ),
        migrations.AddField(
            model_name='student',
            name='churn_risk_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Churn risk yangilangan vaqt'),
        ),
    ]
