# Generated by Django 6.0.3 on 2026-05-31 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('short_text', models.CharField(blank=True, max_length=300, verbose_name='Qisqa matn')),
                ('body', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram havola')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Tepaga qadalgan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
