"""
Django settings for wallstreet project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-c#lhv34i)%n22d9f&d2w$ts1)76zo4$&$kel7l!&ib^b5uq8)8'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default = False (PythonAnywhere/production uchun xavfsiz). Lokal ishlab chiqishda
# .env ichida DEBUG=True qo'ying.
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS — .env: ALLOWED_HOSTS=*  yoki  ALLOWED_HOSTS=domen1.uz,domen2.uz
# Default = '*' — istalgan hostdan (PythonAnywhere domeni ham) qabul qiladi.
_default_hosts = '*'
ALLOWED_HOSTS = [
    h.strip() for h in config('ALLOWED_HOSTS', default=_default_hosts).split(',') if h.strip()
]

# Railway/PythonAnywhere kabi hostlar uchun CSRF ishonchli manzillari
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in config(
        'CSRF_TRUSTED_ORIGINS',
        default='https://*.railway.app,https://*.pythonanywhere.com'
    ).split(',') if o.strip()
]

# Bot tugmalari uchun platforma manzili
WEBSITE_URL = config('WEBSITE_URL', default='http://127.0.0.1:8000')


# Application definition
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tashqi paketlar (mobil API)
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Bizning applar
    'accounts',
    'students',
    'courses',
    'attendance',
    'payments',
    'dashboard',
    'instructors',
    'event_calendar',
    'enrollments',

    # Yangi bo'limlar
    'staff_salary',
    'reports',
    'settings_app',
    'news',
    'api',
]

# ─── REST Framework (mobil ilova API) ────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS — mobil ilova istalgan manzildan ulanishi uchun
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_table",
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS — mobil API uchun
    'whitenoise.middleware.WhiteNoiseMiddleware',  # statik fayllar (host uchun)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wallstreet.error_notifications.DeveloperErrorEmailMiddleware',  # auto-email errors
]

TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
MAX_ADMIN_COUNT = 2
SMS_CODE_EXPIRE_MINUTES = 5

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# ─── Error notifications ─────────────────────────────────────────────────────
# When something goes wrong in the system, an email is automatically sent to
# the developer's inbox.
DEVELOPER_EMAIL = config('DEVELOPER_EMAIL', default='musayevizzatillo58@gmail.com')
SERVER_EMAIL = config('SERVER_EMAIL', default=EMAIL_HOST_USER or DEVELOPER_EMAIL)
ADMINS = [('Wall Street Developer', DEVELOPER_EMAIL)]
MANAGERS = ADMINS

# Route unhandled exceptions to the developer's email even while DEBUG=True.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno}\n{message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Always email errors to the developer (no debug filter), with full traceback.
        'mail_developer': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_developer', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Project-wide logger used by error_notifications.notify_developer
        'wallstreet': {
            'handlers': ['mail_developer', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'wallstreet.urls'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'enrollments.context_processors.telegram_leads',
            ],
        },
    },
]


WSGI_APPLICATION = 'wallstreet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: statik fayllarni siqib uzatish (manifestsiz — xavfsiz)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ─── Production xavfsizligi (faqat DEBUG=False bo'lganda) ────────────────────
# PythonAnywhere saytni HTTPS orqali uzatadi. DEBUG=False bo'lганда quyidagilar
# yoqiladi; lokal HTTP (DEBUG=True) ishini buzmaydi.
if not DEBUG:
    # Proxy (PythonAnywhere) orqasidan HTTPS ni to'g'ri aniqlash
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS — brauzerga doimo HTTPS dan foydalanishni buyuradi (1 yil)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

