"""
Django settings for wallstreet project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-c#lhv34i)%n22d9f&d2w$ts1)76zo4$&$kel7l!&ib^b5uq8)8'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default = False (PythonAnywhere/production uchun xavfsiz). Lokal ishlab chiqishda
# .env ichida DEBUG=True qo'ying.
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS — .env: ALLOWED_HOSTS=*  yoki  ALLOWED_HOSTS=domen1.uz,domen2.uz
# Default = '*' — istalgan hostdan (PythonAnywhere domeni ham) qabul qiladi.
_default_hosts = '*'
ALLOWED_HOSTS = [
    h.strip() for h in config('ALLOWED_HOSTS', default=_default_hosts).split(',') if h.strip()
]

# Railway/PythonAnywhere kabi hostlar uchun CSRF ishonchli manzillari
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in config(
        'CSRF_TRUSTED_ORIGINS',
        default='https://*.railway.app,https://*.pythonanywhere.com,https://*.onrender.com'
    ).split(',') if o.strip()
]

# Bot tugmalari uchun platforma manzili
WEBSITE_URL = config('WEBSITE_URL', default='http://127.0.0.1:8000')


# Application definition
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # allauth talab qiladi

    # Tashqi paketlar (mobil API)
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Google OAuth ("Google bilan kirish") — bepul hostda SMTP'siz kirish
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Bizning applar
    'accounts',
    'students',
    'courses',
    'attendance',
    'payments',
    'dashboard',
    'instructors',
    'event_calendar',
    'enrollments',

    # Yangi bo'limlar
    'staff_salary',
    'reports',
    'settings_app',
    'news',
    'api',
    'teacher_api',   # O'qituvchi mobil ilovasi (DRF + JWT)

    # AI tahlillar (Claude API: churn, o'qituvchi hisoboti, kurs tavsiyasi)
    'ai',
]

# ─── REST Framework (mobil ilova API) ────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS — mobil ilova istalgan manzildan ulanishi uchun
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_table",
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS — mobil API uchun
    'whitenoise.middleware.WhiteNoiseMiddleware',  # statik fayllar (host uchun)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Google OAuth uchun
    'wallstreet.error_notifications.DeveloperErrorEmailMiddleware',  # auto-email errors
]

TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
# Register sahifasida "Botni ochish" havolasi uchun (https://t.me/<username>)
TELEGRAM_BOT_USERNAME = config('TELEGRAM_BOT_USERNAME', default='wall_street_crm_bot')

# ─── Wall Street Technic Bot (texnik yordam) ─────────────────────────────────
# Alohida bot: texnik nosozliklar, parol tiklash va h.k. murojaatlarini qabul
# qiladi → Settings > «Yordam markazi» bo'limiga tushadi. .env ga tokenni yozing:
#   TECHNIC_BOT_TOKEN=123456:ABC...   (@BotFather dan olingan)
TECHNIC_BOT_TOKEN = config('TECHNIC_BOT_TOKEN', default='')
TECHNIC_BOT_USERNAME = config('TECHNIC_BOT_USERNAME', default='wall_street_technic_bot')
# Yangi murojaat kelganda xabar boradigan admin chat ID lari (vergul bilan).
# Bo'sh bo'lsa — DB dagi role='admin' foydalanuvchilarning telegram_chat_id si.
TECHNIC_ADMIN_CHAT_IDS = config('TECHNIC_ADMIN_CHAT_IDS', default='')

# ─── Anthropic Claude AI ─────────────────────────────────────────────────────
# Kalitni .env fayliga yozing: ANTHROPIC_API_KEY=sk-ant-...
# (https://console.anthropic.com → API Keys)
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
# Eslatma: 'claude-sonnet-4-20250514' eskirgan va 2026-06-15 da o'chiriladi.
# Rasmiy o'rnini bosuvchi model — claude-sonnet-4-6.
ANTHROPIC_MODEL = config('ANTHROPIC_MODEL', default='claude-sonnet-4-6')

# ─── Google Gemini AI (asosiy provayder) ─────────────────────────────────────
# Kalitni https://aistudio.google.com/app/apikey dan oling.
# GEMINI_API_KEY sozlangan bo'lsa AI funksiyalar Gemini'dan foydalanadi
# (Anthropic kreditidan mustaqil). Bo'sh bo'lsa — Claude, u ham yo'q bo'lsa
# lokal (offline) tahlil ishlaydi.
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-2.5-flash')

# Churn riski shu chegaradan oshsa avtomatik ogohlantirish yuboriladi
AI_CHURN_ALERT_THRESHOLD = config('AI_CHURN_ALERT_THRESHOLD', default=70, cast=int)
# PythonAnywhere bepul tarif: tashqi internet (api.telegram.org) faqat proxy orqali.
# .env da PROXY_URL=http://proxy.server:3128 (lokalda bo'sh).
PROXY_URL = config('PROXY_URL', default='')
MAX_ADMIN_COUNT = 2
SMS_CODE_EXPIRE_MINUTES = 5

# ─── Onlayn to'lov: Payme ─────────────────────────────────────────────────────
# Payme bilan shartnomadan keyin olinadigan qiymatlar (.env ga yozing):
#   PAYME_MERCHANT_ID=...        (kassa ID)
#   PAYME_KEY=...                (kassa kaliti — PerformTransaction callback uchun)
#   PAYME_TEST_KEY=...           (sandbox kaliti)
# Sandbox (test) rejimi uchun PAYME_TEST=True.
PAYME_MERCHANT_ID = config('PAYME_MERCHANT_ID', default='')
PAYME_KEY = config('PAYME_KEY', default='')
PAYME_TEST_KEY = config('PAYME_TEST_KEY', default='')
PAYME_TEST = config('PAYME_TEST', default=True, cast=bool)
# Checkout sahifasi: prod — https://checkout.paycom.uz, test — https://checkout.test.paycom.uz
PAYME_CHECKOUT_URL = config(
    'PAYME_CHECKOUT_URL',
    default='https://checkout.test.paycom.uz' if PAYME_TEST else 'https://checkout.paycom.uz'
)

# ─── Onlayn to'lov: Click ─────────────────────────────────────────────────────
#   CLICK_SERVICE_ID=...   CLICK_MERCHANT_ID=...   CLICK_SECRET_KEY=...
CLICK_SERVICE_ID = config('CLICK_SERVICE_ID', default='')
CLICK_MERCHANT_ID = config('CLICK_MERCHANT_ID', default='')
CLICK_SECRET_KEY = config('CLICK_SECRET_KEY', default='')
CLICK_CHECKOUT_URL = config('CLICK_CHECKOUT_URL', default='https://my.click.uz/services/pay')

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# ─── Error notifications ─────────────────────────────────────────────────────
# When something goes wrong in the system, an email is automatically sent to
# the developer's inbox.
DEVELOPER_EMAIL = config('DEVELOPER_EMAIL', default='musayevizzatillo58@gmail.com')
SERVER_EMAIL = config('SERVER_EMAIL', default=EMAIL_HOST_USER or DEVELOPER_EMAIL)
ADMINS = [('Wall Street Developer', DEVELOPER_EMAIL)]
MANAGERS = ADMINS

# Route unhandled exceptions to the developer's email even while DEBUG=True.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno}\n{message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Always email errors to the developer (no debug filter), with full traceback.
        'mail_developer': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_developer', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Project-wide logger used by error_notifications.notify_developer
        'wallstreet': {
            'handlers': ['mail_developer', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'wallstreet.urls'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'enrollments.context_processors.telegram_leads',
                'accounts.context_processors.google_oauth',  # "Google bilan kirish" tugmasi
            ],
        },
    },
]


WSGI_APPLICATION = 'wallstreet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Render/Railway kabi hostlar `DATABASE_URL` muhit o'zgaruvchisini beradi
# (PostgreSQL). Agar u bo'lsa — o'shanga ulanamiz; bo'lmasa lokal sqlite3.
#   DATABASE_URL=postgres://user:pass@host:5432/dbname
_database_url = config('DATABASE_URL', default='')
if _database_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=config('DB_SSL_REQUIRE', default=True, cast=bool),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: statik fayllarni siqib uzatish (manifestsiz — xavfsiz)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ─── Media (rasm) saqlash — Render bepul disk EFEMERAL muammosi yechimi ──────
# Render bepul disk redeploy/restart/uxlab-uyg'onishda tozalanadi → yuklangan
# rasm "buzilib"/ko'rinmay qoladi. Doimiy saqlash uchun 3 variant (tartib bilan):
#
#   1) CLOUDINARY_URL bo'lsa → Cloudinary buluti (ba'zi davlatlarda bloklangan).
#   2) USE_DB_MEDIA True bo'lsa → media to'g'ridan-to'g'ri Postgres bazada saqlanadi
#      (chet el xizmati kerak emas, O'zbekistonda ham ishlaydi — TAVSIYA etiladi).
#      Postgres (DATABASE_URL) bor va Cloudinary yo'q bo'lsa — avtomatik yoqiladi.
#   3) Aks holda → lokal disk (lokal development uchun).
CLOUDINARY_URL = config('CLOUDINARY_URL', default='')
USE_DB_MEDIA = config(
    'USE_DB_MEDIA',
    default=bool(_database_url) and not CLOUDINARY_URL,
    cast=bool,
)

if CLOUDINARY_URL:
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }
elif USE_DB_MEDIA:
    INSTALLED_APPS += ['dbmedia']
    STORAGES['default'] = {
        'BACKEND': 'dbmedia.storage.DatabaseStorage',
    }

LOGIN_URL = 'login'
# Google OAuth'dan keyin rolga qarab yo'naltiramiz (admin→dashboard, teacher→davomat)
LOGIN_REDIRECT_URL = '/accounts/post-login/'
LOGOUT_REDIRECT_URL = 'login'

# ─── Google OAuth ("Google bilan kirish") ────────────────────────────────────
# Nima uchun: PythonAnywhere bepul tarif tashqi SMTP'ni bloklaydi, shuning uchun
# Gmail'ga kod yuborib bo'lmaydi. Google OAuth esa brauzer Google'ga yo'naltirishi
# orqali ishlaydi (SMTP kerak emas) — Google domeni PA whitelist'ida.
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',           # username/parol bilan kirish
    'allauth.account.auth_backends.AuthenticationBackend',  # Google OAuth
]

# Google Cloud Console > Credentials > OAuth 2.0 Client ID dan oling.
# Authorized redirect URI: https://SIZNING-DOMEN/accounts/google/login/callback/
GOOGLE_CLIENT_ID     = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')

# Provider sozlamasi to'g'ridan-to'g'ri settings'da — DB'da SocialApp yaratish shart emas.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret':    GOOGLE_CLIENT_SECRET,
            'key':       '',
        },
        'SCOPE':       ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# Bizning maxsus adapter: Google bilan kirgan foydalanuvchini 'teacher' qiladi,
# is_verified=True qo'yadi va Instructor profilini yaratadi.
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.WallStreetSocialAdapter'

SOCIALACCOUNT_LOGIN_ON_GET = True   # tugma bosilganda to'g'ridan-to'g'ri Google'ga
SOCIALACCOUNT_AUTO_SIGNUP  = True   # oraliq forma ko'rsatmasdan ro'yxatga oladi
# Email mos kelsa — mavjud hisobga ulanadi (admin allaqachon ro'yxatdan o'tgan bo'lsa)
SOCIALACCOUNT_EMAIL_AUTHENTICATION              = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# allauth'ning o'z email tasdiqlashini o'chiramiz (SMTP kerak bo'lmasligi uchun)
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS      = {'username'}
ACCOUNT_SIGNUP_FIELDS      = ['username*', 'password1*', 'password2*']

# ─── Production xavfsizligi (faqat DEBUG=False bo'lganda) ────────────────────
# PythonAnywhere saytni HTTPS orqali uzatadi. DEBUG=False bo'lганда quyidagilar
# yoqiladi; lokal HTTP (DEBUG=True) ishini buzmaydi.
if not DEBUG:
    # Proxy (PythonAnywhere) orqasidan HTTPS ni to'g'ri aniqlash
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS — brauzerga doimo HTTPS dan foydalanishni buyuradi (1 yil)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

