# Generated by Django 5.2 on 2026-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_group_teacher_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='course',
            name='weekdays',
            field=models.CharField(blank=True, default='', help_text='Vergul bilan ajratilgan kunlar, masalan: mon,wed,fri', max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('frozen', 'Frozen')], default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('frozen', 'Frozen')], default='active', max_length=20),
        ),
    ]
