# Generated by Django 6.0.3 on 2026-05-31 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')])),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', "To'langan"), ('pending', 'Kutilmoqda')], default='paid', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='instructors.instructor')),
            ],
            options={
                'verbose_name': "Oylik to'lov",
                'verbose_name_plural': "Oylik to'lovlar",
                'ordering': ['-year', '-month', '-paid_at'],
            },
        ),
    ]
