# Generated by Django 6.0.3 on 2026-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
