# Generated by Django 6.0.3 on 2026-06-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_salary', '0002_alter_salarypayment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=10),
        ),
    ]
