# Generated by Django 6.0.3 on 2026-06-12 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('churn', 'Talaba churn bashorati'), ('instructor_report', "O'qituvchi samaradorlik hisoboti"), ('course_recommend', 'Kurs tavsiyasi')], max_length=40, verbose_name='Funksiya')),
                ('related_object', models.CharField(blank=True, default='', max_length=120)),
                ('model_name', models.CharField(blank=True, default='', max_length=80, verbose_name='AI model')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='Yuborilgan prompt')),
                ('response', models.TextField(blank=True, default='', verbose_name='AI javobi')),
                ('success', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('error', models.TextField(blank=True, default='', verbose_name='Xatolik')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='Chaqirgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI log',
                'verbose_name_plural': 'AI loglar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', '-created_at'], name='ai_ailog_feature_45d61d_idx')],
            },
        ),
    ]
