# Generated by Django 6.0.3 on 2026-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(default='Wall Street', max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default="so'm", max_length=10)),
            ],
            options={
                'verbose_name': 'Markaz sozlamasi',
                'verbose_name_plural': 'Markaz sozlamalari',
            },
        ),
    ]
