# Generated by Django 6.0.3 on 2026-06-14 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('password', 'Parolni tiklash'), ('login', 'Tizimga kira olmayapman'), ('payment', "To'lov muammosi"), ('account', 'Hisob / profil muammosi'), ('course', 'Kurs / dars muammosi'), ('bug', 'Texnik xatolik (bug)'), ('other', 'Boshqa muammo')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Mavzu')),
                ('description', models.TextField(verbose_name='Muammo tavsifi')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Murojaatchi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('contact', models.CharField(blank=True, max_length=190, verbose_name='Login / email')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('telegram_username', models.CharField(blank=True, max_length=150)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=10, verbose_name='Muhimlik')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi'), ('closed', 'Yopilgan')], default='new', max_length=15, verbose_name='Holat')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Admin javobi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Texnik murojaat',
                'verbose_name_plural': 'Texnik murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
